# Generated by Django 3.2.9 on 2021-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='thing',
            name='other_things',
            field=models.ManyToManyField(to='my_app.OtherThing'),
        ),
    ]
